services:
  backplanner:
    image: backplanner
    build: "./src/backPlanner"
#    ports:
#      - 8888:8000
  frontPlanner:
    image: front_planner
    build: "./src/frontPlanner"
    ports:
      - 3000:3000
