# database = '/mnt/c/Users/user/Downloads/MPK2.DXDB'
database = 'MPK'
# database = 'C:\\Users\\user\\Downloads\\MPK.DXDB'
host = '10.199.1.11'
# host = '10.199.2.138'
user = 'sysdba'
password = 'F409mZu5'
charset = 'UTF8'

MATTERMOST_URL = 'https://mm-mpk.ru'